### ISSUE TITLE
Question about newline in list

### ISSUE THREAD

**Issue by Narrat** [themoken/canto-curses#24]
https://paste.archlinux.de/OFQqSh/

This blog has the nasty tendency to put \n in the title (I suppose because of the reblogging). Or what is used for item list for displaying. 
Is it possible to filter these from the overview list?

**Comment by themoken** [comment]
I assume you mean filter out the newlines, rather than the whole item.

Yeah, that's a bit tough at the moment, but solving this would also help solve the HTML title problem, even though I'm pretty sure both are *technically* already correct based on how the feed is defined (i.e. the newlines actually exist, and the HTML is double-escaped).

The reader already has a plugin hook to edit the content, so perhaps it's time for the standard story and tag items to as well.

**Comment by Narrat** [comment]
Jeah, just to filter out the newlines

**Comment by themoken** [comment]
I just pushed a cleantitle.py plugin that should handle this newline case, as well as giving you the power to strip anything else out of the story content. Reopen this if it doesn't work for you.

**Comment by Narrat** [comment]
Works like a charm so far :)
